- name: Installing dependencies (RedHat)
  become: yes
  package:
    name: "{{ item }}"
    state: present
  loop:
    - finger
    - cmake 
    - patch
    - gcc
    - make
    - autoconf
    - libtool
    - automake
    - pkgconfig
    - openssl-devel
    - gettext
    - file
    - pam-devel
    - libX11-devel
    - libXfixes-devel
    - libjpeg-devel
    - flex
    - bison
    - gcc-c++
    - libxslt
    - perl-libxml-perl
    - xorg-x11-font-utils
    - xmlto-tex
    - libXrandr-devel
    - nasm
    - xorg-x11-server-devel
    - xorg-x11-server-Xorg
    - xorg-x11-xinit
    - libXfont2
    - libXfont2-devel

- name: Allowing 3389/tcp
  become: yes
  firewalld:
    port: 3389/tcp
    permanent: yes
    state: enabled
  register: rdp_tcp

- name: Allowing 3389/udp
  become: yes
  firewalld:
    port: 3389/udp
    permanent: yes
    state: enabled
  register: rdp_udp

- name: Reloading firewall-cmd
  become: yes
  shell: firewall-cmd --reload
  when: rdp_tcp.changed or rdp_udp.changed